import { execFileSync } from "node:child_process";
import { chmodSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { parseDiff, summarizeDiff } from "../src/diff.ts";

/**
 * Diff parsing against REAL git output (R-7.6, AC-7.18).
 *
 * Fixtures are generated by running git, never committed as text. A hand-written diff fixture tests
 * my idea of git's output, which is exactly the thing that is wrong when a parser is wrong.
 */

const GIT_ENV = {
	...process.env,
	GIT_CONFIG_GLOBAL: "/dev/null",
	GIT_CONFIG_SYSTEM: "/dev/null",
	GIT_CONFIG_NOSYSTEM: "1",
	HOME: "/nonexistent-for-tests",
};

let repo: string;
const g = (...args: string[]): string =>
	execFileSync("git", args, { cwd: repo, encoding: "utf8", env: GIT_ENV, timeout: 15_000 });

beforeAll(() => {
	repo = mkdtempSync(join(tmpdir(), "pi-diff-"));
	g("init", "-q", "-b", "main");
	g("config", "user.email", "x@y.z");
	g("config", "user.name", "X");
});

afterAll(() => {
	rmSync(repo, { recursive: true, force: true });
});

/** Commits a tree, then applies changes, and returns the real `git diff` output. */
function diffFor(setup: () => void, changes: () => void, args: string[] = []): string {
	setup();
	g("add", "-A");
	g("commit", "-qm", `base-${Math.random()}`);
	changes();
	g("add", "-A");
	return g("diff", "--cached", ...args);
}

describe("real git output", () => {
	it("AC-7.18 a simple modification: counts, line numbers and hunk anchor", () => {
		const raw = diffFor(
			() => writeFileSync(join(repo, "a.txt"), "one\ntwo\nthree\n"),
			() => writeFileSync(join(repo, "a.txt"), "one\nTWO\nthree\nfour\n"),
		);
		const d = parseDiff(raw);
		expect(d.files).toHaveLength(1);
		const f = d.files[0]!;
		expect(f.path).toBe("a.txt");
		expect(f.status).toBe("modified");
		expect(f.additions).toBe(2);
		expect(f.deletions).toBe(1);
		expect(f.binary).toBe(false);

		// Line numbers must be right, because a comment anchor that points at the wrong line is worse
		// than no comment.
		const added = f.hunks[0]!.lines.filter((l) => l.kind === "add");
		expect(added.map((l) => l.text)).toEqual(["TWO", "four"]);
		expect(added[0]!.newLine).toBe(2);
		expect(added[0]!.oldLine).toBe(null);
		const deleted = f.hunks[0]!.lines.filter((l) => l.kind === "del");
		expect(deleted[0]!.oldLine).toBe(2);

		expect(f.hunks[0]!.anchor).toBe("a.txt:1");
		expect(summarizeDiff(d)).toBe("1 file · +2 −1");
	});

	it("AC-7.18 a rename is one file, not a delete plus an add", () => {
		const raw = diffFor(
			() => writeFileSync(join(repo, "old-name.txt"), "stable content here\nmore\n"),
			() => {
				g("mv", "old-name.txt", "new-name.txt");
			},
			["-M"],
		);
		const d = parseDiff(raw);
		expect(d.files).toHaveLength(1);
		expect(d.files[0]!.status).toBe("renamed");
		expect(d.files[0]!.path).toBe("new-name.txt");
		expect(d.files[0]!.oldPath).toBe("old-name.txt");
	});

	it("AC-7.18 a mode change with no hunks is still reported as a change", () => {
		const script = join(repo, "run.sh");
		const raw = diffFor(
			() => writeFileSync(script, "#!/bin/sh\necho hi\n"),
			() => chmodSync(script, 0o755),
		);
		const d = parseDiff(raw);
		expect(d.files).toHaveLength(1);
		const f = d.files[0]!;
		// Chmod +x produces old mode/new mode and nothing else. Reporting "no changes" is how a
		// permission fix ships unnoticed.
		expect(f.status).toBe("mode_changed");
		expect(f.oldMode).toBe("100644");
		expect(f.newMode).toBe("100755");
		expect(f.hunks).toEqual([]);
		expect(f.additions).toBe(0);
	});

	it("AC-7.18 / AC-7.19 a binary file is labelled, never rendered", () => {
		const raw = diffFor(
			() => writeFileSync(join(repo, "blob.bin"), Buffer.from([0, 1, 2, 3])),
			() => writeFileSync(join(repo, "blob.bin"), Buffer.from([9, 8, 7, 6, 5])),
		);
		const d = parseDiff(raw);
		expect(d.files[0]!.binary).toBe(true);
		// No lines: rendering binary is how a terminal ends up in a beep loop.
		expect(d.files[0]!.hunks).toEqual([]);
	});

	it("AC-7.18 CRLF content parses without stray carriage returns", () => {
		/**
		 * A CRLF diff carries a trailing \r on every line. Without stripping it, `+` lines are counted
		 * correctly and then rendered with a character the user cannot see but can copy — and any
		 * comparison against expected text fails for invisible reasons.
		 */
		const raw = diffFor(
			() => writeFileSync(join(repo, "crlf.txt"), "alpha\r\nbeta\r\n"),
			() => writeFileSync(join(repo, "crlf.txt"), "alpha\r\nBETA\r\ngamma\r\n"),
		);
		const d = parseDiff(raw);
		const texts = d.files[0]!.hunks.flatMap((h) => h.lines.map((l) => l.text));
		for (const t of texts) expect(t.includes("\r"), JSON.stringify(t)).toBe(false);
		expect(texts).toContain("BETA");
	});

	it("AC-7.18 no-newline-at-EOF is flagged and not counted as a line", () => {
		const raw = diffFor(
			() => writeFileSync(join(repo, "noeol.txt"), "first\nsecond\n"),
			() => writeFileSync(join(repo, "noeol.txt"), "first\nsecond\nthird"),
		);
		const d = parseDiff(raw);
		const f = d.files[0]!;
		expect(f.noNewlineAtEof).toBe(true);
		// The `\ No newline` marker is meta, not a change: counting it shifts every later line number.
		const meta = f.hunks.flatMap((h) => h.lines).filter((l) => l.kind === "meta");
		expect(meta).toHaveLength(1);
		expect(meta[0]!.oldLine).toBe(null);
		expect(meta[0]!.newLine).toBe(null);
	});

	it("AC-7.18 an added and a deleted file are distinguished", () => {
		const raw = diffFor(
			() => writeFileSync(join(repo, "goes.txt"), "bye\n"),
			() => {
				rmSync(join(repo, "goes.txt"));
				writeFileSync(join(repo, "comes.txt"), "hello\nthere\n");
			},
		);
		const d = parseDiff(raw);
		const byStatus = Object.fromEntries(d.files.map((f) => [f.status, f.path]));
		expect(byStatus.deleted).toBe("goes.txt");
		expect(byStatus.added).toBe("comes.txt");
	});

	it("AC-7.18 a path containing a space survives", () => {
		const raw = diffFor(
			() => writeFileSync(join(repo, "with space.txt"), "a\n"),
			() => writeFileSync(join(repo, "with space.txt"), "a\nb\n"),
		);
		const d = parseDiff(raw);
		expect(d.files[0]!.path).toBe("with space.txt");
	});

	it("AC-7.18 multiple hunks in one file each get their own anchor", () => {
		const base = Array.from({ length: 60 }, (_, i) => `line ${i}`).join("\n");
		const raw = diffFor(
			() => writeFileSync(join(repo, "long.txt"), `${base}\n`),
			() => {
				const lines = base.split("\n");
				lines[2] = "CHANGED EARLY";
				lines[50] = "CHANGED LATE";
				writeFileSync(join(repo, "long.txt"), `${lines.join("\n")}\n`);
			},
		);
		const d = parseDiff(raw);
		const f = d.files[0]!;
		expect(f.hunks.length).toBeGreaterThanOrEqual(2);
		// Anchors are distinct and ordered, so two comments on one file cannot collide.
		const anchors = f.hunks.map((h) => h.anchor);
		expect(new Set(anchors).size).toBe(anchors.length);
		expect(anchors[0]).toMatch(/^long\.txt:\d+$/);
	});

	it("AC-7.19 a huge diff keeps truthful counts and drops the body", () => {
		const raw = diffFor(
			() => writeFileSync(join(repo, "huge.txt"), "seed\n"),
			() =>
				writeFileSync(
					join(repo, "huge.txt"),
					`seed\n${Array.from({ length: 5000 }, (_, i) => `new line ${i}`).join("\n")}\n`,
				),
		);
		const d = parseDiff(raw, { maxLinesPerFile: 100 });
		const f = d.files[0]!;
		expect(f.truncated).toBe(true);
		expect(f.hunks).toEqual([]);
		/**
		 * The counts must survive truncation. A summary reading `+0 −0` next to a truncation notice is
		 * worse than no summary, because it looks like an answer.
		 */
		expect(f.additions).toBe(5000);
		expect(summarizeDiff(d)).toContain("+5000");
	});

	it("AC-7.19 a file cap marks the whole diff truncated", () => {
		const raw = diffFor(
			() => {
				for (let i = 0; i < 8; i++) writeFileSync(join(repo, `many-${i}.txt`), "x\n");
			},
			() => {
				for (let i = 0; i < 8; i++) writeFileSync(join(repo, `many-${i}.txt`), "x\ny\n");
			},
		);
		const d = parseDiff(raw, { maxFiles: 3 });
		expect(d.files).toHaveLength(3);
		expect(d.truncated).toBe(true);
		expect(summarizeDiff(d)).toContain("truncated");
	});

	it("AC-7.18 a subdirectory path keeps its full path", () => {
		const raw = diffFor(
			() => {
				mkdirSync(join(repo, "src", "deep"), { recursive: true });
				writeFileSync(join(repo, "src", "deep", "mod.ts"), "export const a = 1\n");
			},
			() => writeFileSync(join(repo, "src", "deep", "mod.ts"), "export const a = 2\n"),
		);
		const d = parseDiff(raw);
		expect(d.files[0]!.path).toBe("src/deep/mod.ts");
	});
});

describe("malformed and hostile input never throws", () => {
	it("an empty or garbage string parses to nothing", () => {
		// The parser also sees output from a HOST over a network, so a truncated read must degrade to
		// "no files" rather than take down a panel.
		for (const raw of ["", "\n\n", "not a diff at all", "diff --git", "@@ orphan hunk @@"]) {
			expect(() => parseDiff(raw), JSON.stringify(raw)).not.toThrow();
		}
		expect(parseDiff("").files).toEqual([]);
		expect(parseDiff("random text").files).toEqual([]);
	});

	it("a diff truncated mid-hunk keeps what it parsed", () => {
		const cut =
			"diff --git a/x.ts b/x.ts\nindex 111..222 100644\n--- a/x.ts\n+++ b/x.ts\n@@ -1,3 +1,4 @@\n ctx\n+added\n";
		const d = parseDiff(cut);
		expect(d.files).toHaveLength(1);
		expect(d.files[0]!.additions).toBe(1);
	});

	it("a hunk header with omitted counts defaults to one line", () => {
		// `@@ -5 +5 @@` is a single-line hunk. Defaulting the count to 0 makes every later line wrong.
		const raw = "diff --git a/y.ts b/y.ts\n@@ -5 +5 @@\n-old\n+new\n";
		const d = parseDiff(raw);
		const h = d.files[0]!.hunks[0]!;
		expect(h.oldCount).toBe(1);
		expect(h.newCount).toBe(1);
		expect(h.oldStart).toBe(5);
	});

	it("no catastrophic backtracking on a hostile diff", () => {
		/**
		 * Two production ReDoS bugs (122s and 14s) came from unbounded quantifiers, so every new regex on
		 * external input gets timed. The hunk header uses `\d{1,10}`.
		 */
		const hostile = `diff --git a/z b/z\n@@ ${"-".repeat(50_000)}${"9".repeat(50_000)} @@\n`;
		const t0 = performance.now();
		parseDiff(hostile);
		expect(performance.now() - t0).toBeLessThan(200);
	});

	it("a line with an unexpected marker ends the hunk without throwing", () => {
		const raw = "diff --git a/q b/q\n@@ -1,2 +1,2 @@\n ctx\n?weird\n+never reached\n";
		const d = parseDiff(raw);
		expect(d.files[0]!.hunks[0]!.lines.map((l) => l.kind)).toEqual(["ctx"]);
	});

	it("a quoted path with unusual bytes is unquoted", () => {
		const raw = 'diff --git "a/odd\\tname.txt" "b/odd\\tname.txt"\n@@ -1 +1 @@\n-a\n+b\n';
		const d = parseDiff(raw);
		expect(d.files[0]!.path).toContain("odd");
		expect(d.files[0]!.path.startsWith("b/")).toBe(false);
	});
});

describe("header parsing fallbacks (DoD: 100% branches on diff parsing)", () => {
	it('a header with no " b/" separator still yields both paths', () => {
		/**
		 * `git diff --no-prefix` emits `diff --git x.ts x.ts`, with no `a/`/`b/` at all. It is a
		 * configurable option (`diff.noprefix`), so a user with it set would otherwise see every path
		 * come back empty — a silent, total failure of the Changes panel for one config flag.
		 */
		const raw = "diff --git noprefix.ts noprefix.ts\n@@ -1 +1 @@\n-a\n+b\n";
		const d = parseDiff(raw);
		expect(d.files[0]!.path).toBe("noprefix.ts");
		expect(d.files[0]!.additions).toBe(1);
	});

	it("a single-token header does not produce undefined paths", () => {
		// Degenerate, and the point is that it yields a string rather than crashing a render.
		const d = parseDiff("diff --git solo\n@@ -1 +1 @@\n+x\n");
		expect(typeof d.files[0]!.path).toBe("string");
	});

	it("a malformed quoted header falls through to positional parsing", () => {
		// An opening quote with no closing pair: the quoted branch declines and the ` b/` scan handles it.
		const raw = 'diff --git "a/half-quoted.txt b/half-quoted.txt\n@@ -1 +1 @@\n-a\n+b\n';
		const d = parseDiff(raw);
		expect(d.files[0]!.path).toBe("half-quoted.txt");
	});

	it("a path that legitimately begins with a or b is not truncated", () => {
		/**
		 * `stripPrefix` removes a leading `a/` or `b/`, so a real directory called `api/` must survive —
		 * the prefix is exactly two characters plus a slash, not any leading letter.
		 */
		const raw = "diff --git a/api/routes.ts b/api/routes.ts\n@@ -1 +1 @@\n-a\n+b\n";
		expect(parseDiff(raw).files[0]!.path).toBe("api/routes.ts");

		const bare = "diff --git alpha.txt alpha.txt\n@@ -1 +1 @@\n-a\n+b\n";
		expect(parseDiff(bare).files[0]!.path).toBe("alpha.txt");
	});
});

describe("copy detection and truncation edges (DoD: 100% branches)", () => {
	it("AC-7.18 a copied file records its source", () => {
		/**
		 * `git diff -C` reports a copy rather than an addition when a new file's content mostly matches
		 * an existing one. Treating it as a plain addition loses the provenance a reviewer wants most:
		 * "this is that file, adapted".
		 */
		const raw = [
			"diff --git a/orig.ts b/copy.ts",
			"similarity index 92%",
			"copy from orig.ts",
			"copy to copy.ts",
			"@@ -1,3 +1,3 @@",
			" shared",
			"-was",
			"+now",
			"",
		].join("\n");
		const d = parseDiff(raw);
		const f = d.files[0]!;
		expect(f.status).toBe("copied");
		expect(f.oldPath).toBe("orig.ts");
		expect(f.path).toBe("copy.ts");
	});

	it("AC-7.18 a GIT binary patch is labelled without being parsed", () => {
		// `git diff --binary` emits a literal patch body. It must be labelled, never walked as text.
		const raw = "diff --git a/img.png b/img.png\nGIT binary patch\ndelta 42\nzcmV随机字节\n";
		const d = parseDiff(raw);
		expect(d.files[0]!.binary).toBe(true);
		expect(d.files[0]!.hunks).toEqual([]);
	});

	it("AC-7.19 truncation stops counting at the next file, not at the end of the diff", () => {
		/**
		 * The count-only loop after truncation must stop at the next `diff --git`, or one huge file
		 * swallows the counts of every file after it and the second file reports zero changes.
		 */
		const huge = Array.from({ length: 300 }, (_, i) => `+line ${i}`).join("\n");
		const raw = [
			"diff --git a/big.txt b/big.txt",
			"@@ -1,1 +1,301 @@",
			" seed",
			huge,
			"diff --git a/small.txt b/small.txt",
			"@@ -1,1 +1,2 @@",
			" keep",
			"+added here",
			"",
		].join("\n");

		const d = parseDiff(raw, { maxLinesPerFile: 50 });
		expect(d.files).toHaveLength(2);

		const big = d.files.find((f) => f.path === "big.txt")!;
		expect(big.truncated).toBe(true);
		expect(big.additions).toBe(300);

		// The second file is parsed normally and keeps its body.
		const small = d.files.find((f) => f.path === "small.txt")!;
		expect(small.truncated).toBe(false);
		expect(small.additions).toBe(1);
		expect(small.hunks).toHaveLength(1);
	});

	it("AC-7.19 deletions are counted during truncation too", () => {
		const gone = Array.from({ length: 200 }, (_, i) => `-line ${i}`).join("\n");
		const raw = `diff --git a/cut.txt b/cut.txt\n@@ -1,201 +1,1 @@\n ${"seed"}\n${gone}\n`;
		const d = parseDiff(raw, { maxLinesPerFile: 20 });
		expect(d.files[0]!.truncated).toBe(true);
		expect(d.files[0]!.deletions).toBe(200);
	});
});

describe("truncation across multiple hunks (DoD: the last uncovered branch)", () => {
	it("AC-7.19 a file whose FIRST hunk blows the budget still counts later hunks", () => {
		/**
		 * The case the earlier truncation tests missed, and it took reading the coverage report to see
		 * why: when a file has one hunk, the body loop has already counted everything by the time the
		 * budget check runs, so the count-only loop never executes. It only matters for a file whose
		 * first hunk exceeds the budget and which has MORE hunks after it — the count loop walks those.
		 *
		 * Without it, a 3000-line change would report only the lines in its first hunk and the summary
		 * would understate the diff, which is the failure that erodes trust in every number the tool shows.
		 */
		const hunk1 = Array.from({ length: 120 }, (_, i) => `+early ${i}`).join("\n");
		const raw = [
			"diff --git a/multi.txt b/multi.txt",
			"@@ -1,1 +1,121 @@",
			" seed",
			hunk1,
			"@@ -200,2 +320,3 @@",
			" context",
			"+late addition",
			"-late removal",
			"@@ -400,1 +500,2 @@",
			" more context",
			"+final addition",
			"",
		].join("\n");

		const d = parseDiff(raw, { maxLinesPerFile: 50 });
		const f = d.files[0]!;
		expect(f.truncated).toBe(true);
		expect(f.hunks).toEqual([]);
		// 120 from the first hunk, plus 2 from the hunks the count-only loop walked.
		expect(f.additions).toBe(122);
		expect(f.deletions).toBe(1);
		expect(summarizeDiff(d)).toBe("1 file · +122 −1");
	});

	it("AC-7.19 counting past the budget stops at the next FILE, not the next hunk", () => {
		// Same shape, with a second file after it, to prove the boundary is the file and not the hunk.
		const hunk1 = Array.from({ length: 80 }, (_, i) => `+a${i}`).join("\n");
		const raw = [
			"diff --git a/one.txt b/one.txt",
			"@@ -1,1 +1,81 @@",
			" seed",
			hunk1,
			"@@ -90,1 +180,2 @@",
			" ctx",
			"+tail of one",
			"diff --git a/two.txt b/two.txt",
			"@@ -1,1 +1,2 @@",
			" ctx",
			"+belongs to two",
			"",
		].join("\n");

		const d = parseDiff(raw, { maxLinesPerFile: 30 });
		expect(d.files).toHaveLength(2);
		expect(d.files[0]!.additions).toBe(81);
		// The second file's addition must not have been swallowed by the first file's count loop.
		expect(d.files[1]!.additions).toBe(1);
		expect(d.files[1]!.truncated).toBe(false);
	});
});
